<?php

declare(strict_types=1);

namespace framework\database;

class DbConnection extends \PDO
{

    /**
     * @param string $dsn
     * @param string $username
     * @param string $passwd
     * @author Therion86
     */
    public function __construct(string $dsn, string $username, string $passwd)
    {
        parent::__construct($dsn, $username, $passwd);
        $this->setAttribute(\PDO::ATTR_STATEMENT_CLASS, array(DbStatement::class, array($this)));
    }

    /**
     * @param string $statement
     * @param array $driver_options
     * @return bool|DbStatement|void
     * @author Therion86
     */
    public function prepare($statement, $driver_options = null): DbStatement
    {
        return parent::prepare($statement, $driver_options); // TODO: Change the autogenerated stub
    }
}